<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1bca2423e08a9a31292830517ecf3d17
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'ReCaptcha\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ReCaptcha\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1bca2423e08a9a31292830517ecf3d17::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1bca2423e08a9a31292830517ecf3d17::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1bca2423e08a9a31292830517ecf3d17::$classMap;

        }, null, ClassLoader::class);
    }
}
